### ISSUE TITLE
Make predicates-only file compatible with aces-cli and revamp predicates overriding 

### ISSUE THREAD

**Issue by justin13601** [justin13601/ACES#102]
Functionality of #42 but usable in aces-cli as opposed to only in Python API

**Comment by mmcdermott** [comment]
So, interface questions/thoughts:
  1. Suppose we have a criteria file like this: https://github.com/mmcdermott/MEDS-DEV/blob/main/src/MEDS-DEV/tasks/criteria/readmission/general_hospital/30d.yaml How should one include / indicate predicates that are to be overloaded in that file? Should they use `predicate_name: {code: ???}`? `predicate_name: null`? `predicate_name: ???`? Something else?
  2. Can we have there be multiple predicates files that can all be joined together? E.g., if I have a directory of different predicate files for MIMIC, they can all be joined as desired?
  3. What happens if a user wants to overwrite a derived predicate that is defined in the criteria file for a specific dataset? Will that work too?

**Comment by justin13601** [comment]
> 1. Suppose we have a criteria file like this: https://github.com/mmcdermott/MEDS-DEV/blob/main/src/MEDS-DEV/tasks/criteria/readmission/general_hospital/30d.yaml How should one include / indicate predicates that are to be overloaded in that file? Should they use `predicate_name: {code: ???}`? `predicate_name: null`? `predicate_name: ???`? Something else?

Currently, I am thinking that if one specifies `predicates_filepath` in the hydra config, then predicates will be loaded from the yaml, and whatever is under the `predicates` key for the criteria file is ignored.

> 2. Can we have there be multiple predicates files that can all be joined together? E.g., if I have a directory of different predicate files for MIMIC, they can all be joined as desired?

Unfortunately only one predicate file is supported at the moment. This could also be changed to allow `predicates_dir` if you believe this is useful? In this case the directory will have to have only predicates yamls (ie. yamls with only `predicates` fields)

> 3. What happens if a user wants to overwrite a derived predicate that is defined in the criteria file for a specific dataset? Will that work too?

Should work as long as the plain predicates that they depend on are also included in the overwriting file.

Just to clarify, it is currently overwriting the entire `predicates` field when a separate file is provided, rather than individual predicates (ie., overwriting select predicates from the separate file by specifying something in the critiera file) - is this behaviour needed?

**Comment by mmcdermott** [comment]
> Currently, I am thinking that if one specifies `predicates_filepath` in the hydra config, then predicates will be loaded from the yaml, and whatever is under the `predicates` key for the criteria file is ignored.

I don't think that works. What about derived predicates specific to the task? Those we still want to be able to be specified in the task criteria file and not have them be dropped.

> Unfortunately only one predicate file is supported at the moment. This could also be changed to allow predicates_dir if you believe this is useful? In this case the directory will have to have only predicates yamls (ie. yamls with only predicates fields)

That's fine. Let's stick with one file for now and we can expand as needed. We'll modify the structure of MEDS-DEV so that there is just one predicates.yaml file in the dataset folder.

**Comment by justin13601** [comment]
> I don't think that works. What about derived predicates specific to the task? Those we still want to be able to be specified in the task criteria file and not have them be dropped.

Ah I see, well I thought derived predicates would also be included in this separate predicates.yaml, and if they were not referenced in the task critiera, they don't matter. But you're saying it would be better to only have plain predicates in the separate file?

**Comment by mmcdermott** [comment]
It could be a mix; basically, I think the logic should be something like this:

in a "criteria" file, predicates that are defined with `predicate_name: ???` are those that _must_ be found in the "predicates" file for the task to be valid. other predicates can be used from the "criteria" file if they are present.

**Comment by mmcdermott** [comment]
we could use `null` / `None` instead of `???` too, of course; I just like `???` as it is the symbol for "must be overwritten" in OmegaConf

**Comment by justin13601** [comment]
Ah I see what you mean - I think that will require some changes to the Python API also, I will get on that

**Comment by justin13601** [comment]
I attempted some changes in #124 but would like some clarifications @mmcdermott:

1. I think there is a difference between storing predicates entirely in a different file (originally implemented, simply to keep the task criteria file short and clean) vs. overriding predicates from a separate file (via '???' for example). If we implement overriding, then it would be assumed that all referenced predicates need to be defined in the critiera file, either with "???" or explicitly coded? Or is both functionality (loading + overriding) wanted where we try to load any unresolved predicates used in the critiera from the separates predicates-only file?

2. If both to 1), then I'm not sure what the best logic is. Does the following make sense?
- Check if a separate filepath is provided for predicates (either Python API or aces-cli)
- Get a list of all referenced predicates by iterating through defined criteria (windows + trigger etc.)
- Override all predicates with instances of "???" in the criteria file using definitions from the separate predicates file
- Verify if all referenced predicates exist between these two sets of predicates (critiera predicates with overrides + predicates from separate file), else raise error
- Only compute predicate columns from the list of referenced predicates

**Comment by mmcdermott** [comment]
I think you could do something simple and stupid for now and just basically make a new predicates dictionary that is 
```python
new_predicates = {
  **criteria_file.predicates,
  **predicates_file.predicates,
}
```
then use your existing logic to filter it down to only use the needed predicates. That would still support loading new predicates, overwriting existing predicates, and relying on critieria-file-only derived predicates, right?
