### ISSUE TITLE
Bugs + Features

### ISSUE THREAD

**Issue by justin13601** [justin13601/ACES#3]
Bugs/Features

**Comment by mmcdermott** [comment]
For config default values and getting, two options:
1. Make the config a dataclass object, where unset fields or None have defaults of the appropriate type
2. Define `get_config` helper as:
```python
def get_config(cfg: dict, key: str, default: Any) -> Any:
  if key not in cfg or cfg[key] is None: return default
  return cfg[key]
```

**Comment by justin13601** [comment]
Throw error for end if start and duration are defined

**Comment by justin13601** [comment]
Beginning of record must be `start: None`  in YAML
