### ISSUE TITLE
ACES should provide a utility to take a generic predicates file and a criteria file and merge the two to make a dataset specific task config

### ISSUE THREAD

**Issue by justin13601** [justin13601/ACES#42]
In this setting, the `predicates.yaml` file would be dataset specific and have all predicates recognized for that dataset. The `criteria.yaml` file would be task, not dataset specific, and would match (by name) the predicates from the dataset to those used in the task to build and store a dataset specific task file.

**Comment by mmcdermott** [comment]
Closed by #82
