### ISSUE TITLE
MEDS Benchmark v0.0.1 Predicates Expansion

### ISSUE THREAD

**Issue by justin13601** [justin13601/ACES#47]
- [ ] #87
- [ ] #90

**Comment by justin13601** [comment]
We hope to support more complex predicates that are not expressed as codes in datasets (ie., those that require aggregations of medians/running averages over time to measure disease progression), as well as derived predicates with `not()` or nested boolean logic. In both cases, predicates can currently be specified manually by creating the predicates dataframe directly.

**Comment by justin13601** [comment]
We hope to support SQL for the creation of predicate columns via the [new polars function ](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.sql.html)!

**Comment by justin13601** [comment]
Similar to #47

**Comment by mmcdermott** [comment]
Some of the component issues are more urgent, whereas this larger tracking issue has other elements that are less urgent.

**Comment by mmcdermott** [comment]
FYI @justin13601 I'm adjusting this to cover the two more urgent immediate tasks only.

**Comment by mmcdermott** [comment]
Closing in favor of just tracking the other two directly.
