### ISSUE TITLE
Better handle criteria for static variables

### ISSUE THREAD

**Issue by justin13601** [justin13601/ACES#48]
- [ ] Ensure static inclusion is better handled as currently it can only be expressed as a predicate with MEDS

**Comment by justin13601** [comment]
Similar to #47

**Comment by mmcdermott** [comment]
So, there are a few ways static data can be expressed:
1. In ESGPT, there is a separate dataframe for static data.
2. In MEDS, static data has null timestamps.
3. In manually extracted predicates, there is (currently) no notion of static data.

I suggest that we do the following:
1. In the extracted predicates dataframe, a single row with a null timestamp reflects "static" observations. This is true regardless of whether the source is MEDS, ESGPT, or manually extracted.
2. Then we need to define a way in the configuration file to express static constraints. Here, we have some flexibility. I suggest that, for now, we add a `"patient_demographics"` section to the configuration file separate from `"windows"` that imposes constraints on the null timestamp row, apply that before the trigger, then remove the null predicates row and proceed as planned. The `"patient_demographics"` section would contain merely the (static only) constraints imposed over the entire population. However, this should be noted to potentially be something that changes in the future and we should have an open github issue in addition to this issue which can track these changes for community contributions on revisions to the API, which we link in the documentation.

Thoughts?

**Comment by justin13601** [comment]
Yep that makes sense, I'll add this - separating static variables out into another section is much cleaner than trying to integrate it into a particular window. It's also over the entire population anyway and that way we won't have too alter the actual extraction at the moment.

**Comment by justin13601** [comment]
Would it be better to filter for static critera before creating the final predicates dataframe (ie. getting derived predicates and cleaning up) or after?

Advantage of doing it before is that there would be less rows used to calculate the predicates, which should reduce compute needed since it was the most memory intensive step from the profiling. However, the number of rows excluded would be based on the number of raw rows as opposed to the number of processed predicates dataframe rows (which is used during the recursion, numbers are inconsistent).

The other option is to switch all to show the number of patients excluded as opposed to rows, then it wouldn't matter and it be better to filter before creating predicate dataframe

**Comment by mmcdermott** [comment]
The thing to focus on here is computational simplicity (e.g., code simplicity). So I would break it down like this:

1. Compute the predicates dataframe with statics as null timestamps, otherwise unmodified.
2. Remove the rows with null timestamps and evaluate any static constraints and use that to filter the possible trigger events.
3. Proceed with the recursive algorithm like normal.

**Comment by justin13601** [comment]
I guess my question was originally re: 1, since computing the predicates dataframe would group all the null timestamp rows together, so I would have to take out the null timestamp rows, compute predicates, and then add them back in. If I am already taking them out prior to computing the predicates dataframe, I was wondering if it would be better to filter the input dataframe first so that computing predicates costs less computationally

**Comment by mmcdermott** [comment]
Why not just let it group the null timestamp rows together and compute the aggregate predicates as normal? What problem does that cause? Static predicates are just normal predicates with null timestamps, so should be able to be treated as such in all instances, as far as I can figure.

**Comment by justin13601** [comment]
Oh I see what you mean now, I thought we wouldn't create predicate columns for static variables but I guess it would make sense to directly treat it as plain predicates as you said!

**Comment by mmcdermott** [comment]
Closed by #82
