### ISSUE TITLE
Match the MEDS label schema for MEDS dataset

### ISSUE THREAD

**Issue by mmcdermott** [justin13601/ACES#72]
https://github.com/Medical-Event-Data-Standard/meds/blob/main/src/meds/schema.py#L67

**Comment by justin13601** [comment]
Add some renames at the end for col names, maybe a toggle for default vs. MEDS label

**Comment by mmcdermott** [comment]
We'll want to explicitly validate against the imported MEDS schema, much as I do in MEDS transforms here: https://github.com/mmcdermott/MEDS_transforms/blob/main/src/MEDS_transforms/extract/finalize_MEDS_data.py#L15

Note this code may eventually move to the `meds` repo proper, per https://github.com/Medical-Event-Data-Standard/meds/issues/37

**Comment by justin13601** [comment]
Done in #80
