### ISSUE TITLE
Expand shards should accept a slightly more permissive string formatting language to capture shards with prefixes other than ".*/"

### ISSUE THREAD

**Issue by mmcdermott** [justin13601/ACES#77]
E.g., the old MEDS MIMIC ETL writes out files like "data/data_0.parquet", etc. -- we need a way to express this. An alternative is to just have expand shards take the data root and just do a glob directly, so it can capture everything. Or to support both. 

Tagging @cpitsch for tracking

**Comment by justin13601** [comment]
What is an example of this?

Currently, something like `expand_shards("train/4")` works, but what else needs to be supported?

**Comment by mmcdermott** [comment]
For you to be able to run it with the arg `data/data_4` and get out
`data/data_0`, `data/data_1`, etc
