### ISSUE TITLE
Expand Predicate Support to Include Lists of Values and Regex Matching

### ISSUE THREAD

**Issue by mmcdermott** [justin13601/ACES#90]
Patterns for this issue:
- [x] Regexes
- [x] Any of a list of target values.

**Comment by mmcdermott** [comment]
To implement this most easily, I'd recommend following a two-stage process like I do in https://github.com/mmcdermott/MEDS_transforms/blob/dev/src/MEDS_transforms/extract/parser.py, where the user input (e.g., in the ACES task config yaml file) first gets parsed into a structured form of the predicate, and then the structured predicate form gets mapped into the MEDS or ESGPT or direct `pl.Expr`s. That way your structured form can be very explicit like "{regex: blah}" and "{literal: foo}" and "{any_of: [blah]}" and your input form can (if desired, though it is not necessary) be more flexible.

**Comment by justin13601** [comment]
> To implement this most easily, I'd recommend following a two-stage process like I do in https://github.com/mmcdermott/MEDS_transforms/blob/dev/src/MEDS_transforms/extract/parser.py, where the user input (e.g., in the ACES task config yaml file) first gets parsed into a structured form of the predicate, and then the structured predicate form gets mapped into the MEDS or ESGPT or direct `pl.Expr`s. That way your structured form can be very explicit like "{regex: blah}" and "{literal: foo}" and "{any_of: [blah]}" and your input form can (if desired, though it is not necessary) be more flexible.

Any particular thoughts on the input form? Would it be reasonable to emulate derived predicates and allow plain predicate codes to be `any(str1, str2)`, `all(str1, str2)`, and `regex(expr)`?

**Comment by mmcdermott** [comment]
In terms of format, we should, if possible, we should try to enable sharing of this matching code with MEDS-Transform which has similar uses for matching parts of MEDS data. If we do that, it would also potentially solve #87.
